### ISSUE TITLE
Nested mruby Rust calls cause memory leaks in the case of uncaught exceptions.

### ISSUE THREAD

**Issue by vktec** [anima-engine/mrusty#90] opened 2016-11-03 09:45 UTC
Currently, to raise errors within Ruby from Rust, I'm using the following:

```rust
mruby
    .run("self")
    .unwrap()
    .call("raise",
           vec!(mruby.string(my_error_message)))
    .unwrap()

```

I noticed that there's a method on `Mruby` named `raise`, but it's a private method.
What are the reasons behind this decision? Would it be easy to make it public, or should I continue using my current workaround?

**Comment by dragostis** [comment] 2016-11-03 10:35
I can't remember the exact details, but I'm afraid that might cause undefined behaviour because of the return types in `mrfn!` which is why I left it out. I would recommend using `panic!` on the Rust side of things.

**Comment by dragostis** [comment] 2016-11-03 10:37
If I remember correctly, raising inside of Rust code causes "rusty" mruby-owned Rust objects to be forgotten by the GC without calling `drop`. You might want to look into this.

**Comment by vktec** [comment] 2016-11-03 10:49
> If I remember correctly, raising inside of Rust code causes "rusty" mruby-owned Rust objects to be forgotten by the GC without calling drop. You might want to look into this.

That's interesting. I've been having that exact issue when calling undefined methods using `Mruby::run` (though I've not managed to figure out exactly what's causing the issue yet). Any ideas on what/where the problem may be?

**Comment by dragostis** [comment] 2016-11-03 11:06
This [callback](https://github.com/mruby/mruby/blob/master/include/mruby/data.h#L27) needs to let Rust know that the data type is no longer in the GC and that the memory can be freed. You might want to check out the [free function](https://github.com/anima-engine/mrusty/blob/master/src/mruby.rs#L1015) and see whether it gets called when raise happens. If not, there needs to be a way to intercept raising and free all objects after it, but I'm not quite sure it's possible.

**Comment by vktec** [comment] 2016-11-06 12:17
While I'm not able to figure out what's actually going on, I've thrown some code around and figured out that I'm only hitting up against this issue when I call a Rust function that calls `Mruby::run` from mruby code.
There may be other things that trigger it, but that's all I've been able to figure out so far.

Here's what I've come up with:

```rust
#[macro_use]
extern crate mrusty;
use mrusty::*;

#[derive(Debug)]
struct Foo(String);
impl Foo {
    pub fn new(name: &str) -> Foo {
        let slf = Foo(name.to_string());
        println!("New {:?}", slf);
        slf
    }
}

impl Drop for Foo {
    fn drop(&mut self) {
        println!("Dropping {:?}", self);
    }
}

fn working() {
    let mrb = Mruby::new();
    mrb.def_class_for::<Foo>("Foo");
    mrb.def_method_for::<Foo, _>(
        "initialize",
        mrfn!(|_mrb, slf: Value, name: (&str)| {
            slf.init(Foo::new(name))
        }));

    // Works fine
    mrb.run(r#"
    foo = Foo.new "a"
    bar
    "#).ok();
}

fn broken() {
    let mrb = Mruby::new();
    mrb.def_class_for::<Foo>("Foo");
    mrb.def_method_for::<Foo, _>(
        "initialize",
        mrfn!(|_mrb, slf: Value, name: (&str)| {
            slf.init(Foo::new(name))
        }));

    mrb.def_class_method_for::<Foo, _>(
        "eval",
        mrfn!(|mrb, _slf: Value, expr: (&str)| {
            mrb.run(expr).unwrap()
        }));

    // Works fine on it's own
    mrb.run(r#"
    foo = Foo.new "a"
    bar
    "#).ok();

    // This breaks it
    mrb.run(r#"
    foo = Foo.new "c"
    Foo.eval "bar"
    "#).ok();
}

fn main() {
    working();
    broken();
}
```

**Comment by dragostis** [comment] 2016-11-06 14:41
@vktec It seems like the problem is caused by `Mruby` not dropping. In the `broken` example `mrb` doesn't call `drop` which would normally call `close` on the mruby state.

**Comment by dragostis** [comment] 2016-11-06 14:50
@vktec Got it: this happens because mruby interrupts Rust's usual runtime. Let me explain.

You start by calling mruby from Rust:
```
mrb.run(...);
```

Then mruby calls back into Rust:
```
...
Foo.eval ...
```

Rust calls back into mruby which breaks:
```
 mrb.run(expr).unwrap()
```

When `eval` runs, the internal Rust mruby state pointer (which is an `Rc`) is borrowed. Because mruby totally breaks, it interrupts the Rust code that does the borrowing, so the mruby `Rc` never gets back decremented.

I currently have no solution to this problem.

**Comment by vktec** [comment] 2016-11-06 15:36
Would it be possible to change the handling of undeclared methods to return an `Err`, rather than crashing? That way, Rust would be in control of the process and the `Rc` would be decremented properly, correct?

**Comment by dragostis** [comment] 2016-11-06 15:46
I think mrusty needs to handle any exception that mruby might cause. So, whenever you run anything in mruby, any exception should be captured to prevernt crashes.

**Comment by vktec** [comment] 2016-11-06 15:57
Yep, that sounds like a good idea. Any ideas how that could be achieved? I'd be willing to help out with this if it's needed.

**Comment by dragostis** [comment] 2016-11-07 09:38
Of course. The problem arises when running [`method`](https://github.com/anima-engine/mrusty/blob/master/src/mruby.rs#L1079) gets interrupted. This leads to the [self `value` that clones `mruby`](https://github.com/anima-engine/mrusty/blob/master/src/mruby.rs#L1066) not being dropped at the [end of the block](https://github.com/anima-engine/mrusty/blob/master/src/mruby.rs#L1097).

There might be a way to prevent the drop from not being triggered, but I doubt it. I'm tempted to ask about this issue on mruby as well to see whether there is a better solution than surrounding everything in a begin/catch block. The current exception handling works by calling [`mrb_ext_get_exc`](https://github.com/anima-engine/mrusty/blob/master/src/mruby.rs#L1180).

**Comment by dragostis** [comment] 2016-11-07 09:45
Also, after fixing this `raise` should become public.

**Comment by AndyBarron** [comment] 2016-11-12 09:53
I wonder if you could wrap the value in some kind of newtype with a custom drop or something ([newtype example](https://github.com/AndyBarron/app-dirs-rs/blob/a0bae68/src/imp/platform/windows.rs#L61), [usage example](https://github.com/AndyBarron/app-dirs-rs/blob/a0bae68/src/imp/platform/windows.rs#L89)). I know it's not exactly like the example I linked, but perhaps something similar could work here?

**Comment by dragostis** [comment] 2016-11-12 09:59
@AndyBarron I don't think that would work in this particular case. An ideal solution here would be to inform mruby that it should not give up on running thr Rust part even if it has an unhandled exception.

**Comment by AndyBarron** [comment] 2016-11-12 10:00
Yeah, looking at it more, I don't think so either. I wonder if it's something we can even handle from the Rust side... Hmm.

**Comment by dragostis** [comment] 2016-11-12 10:05
@AndyBarron I don't think there is apart from removing the `Rc` around the mruby state pointer and forcing people to close it manually which js rather unfortunate.

Maybe, still, you could have a stack of `Value` objects that you need to handle when mruby runs into an unhandled exception. So, when mruby exits okay, you just pop them from the stack, when it doesn't, you pop them and unsafely decrement the `Rc` for every `Value`.

**Comment by dragostis** [comment] 2016-11-22 13:16
The solution to this issue appears to be wrapping up **every** mruby call that might trigger an exception in C try-catch clauses and handle the return/exception in Rust similar to [`mrb_protect`](https://github.com/mruby/mruby/blob/master/mrbgems/mruby-error/src/exception.c#L6).

Unfortunately, in order to ensure safety, `Mruby::raise` cannot be made public, since will break the usual Rust runtime and prevent any deallocations from being made. The alternative to this will remain `panic!`.

**Closed** 2016-11-23 19:38 UTC
Labels: bug
